AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Development launch:
  ```
  sam local start-api -t ./local.yml --parameter-overrides `cat ./.env` -l message.log -p 3015
  ```
Parameters:
  PackageTable:
    Type: String
  TrackerLocationTable:
    Type: String
Resources:
  TrackerLocationUpdaterLambda:
    Properties:
      CodeUri: ./
      Description: update tracker location
      Environment:
        Variables:
          PACKAGE_TABLE: !Ref 'PackageTable'
          TRACKER_LOCATION_TABLE: !Ref 'TrackerLocationTable'
      Events:
        HttpGet:
          Properties:
            Method: GET
            Path: /
          Type: Api
        HttpOptions:
          Properties:
            Method: OPTIONS
            Path: /
          Type: Api
        HttpPost:
          Properties:
            Method: POST
            Path: /
          Type: Api
      Handler: src/index.handler
      Runtime: nodejs16.x
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
