jobs:
  lint-format-properties:
    name: Format Properties
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Run Sort for *.properties
        run: |
          git ls-files '*.properties' | xargs -I {} sort -c {}
  lint-format-yaml:
    name: Format yaml
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          architecture: 'x64'
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install yq
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Run yq
        run: |
          git ls-files '*.yml' '*.yaml' | xargs -I {} yq -i -S -Y . {}
          git diff
          git diff-index --quiet HEAD --
  prettier:
    name: Format JS
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install -g pnpm prettier
      - name: Install dependencies
        run: make
      - name: Run prettier
        uses: wearerequired/lint-action@v2
        with:
          prettier: true
name: Format
'on':
  - push
